### PR TITLE
[76] fix missing resource issue on treeview

### PR DESCRIPTION
**Pull request by connectbo**
This pr lets treeview load all resources, not only the ones on tableview, but we have to set a `limit` in the rest api call, would 500 be enough?

### CODE REVIEW

**Comment by trel** [comment]
hmm, what if we DON'T set a limit?

**Comment by trel** [comment]
or zero (`0`)?

**Comment by trel** [comment]
i confirm the new code (with 500) works as designed.

**Comment by connectbo** [comment]
I just experimented with setting limit as zero, and it's returning the full resource array as expected. Feels like it should be it.

**Comment by trel** [comment]
yes, ship it.   Please #.

**Comment by connectbo** [comment]
# added, ready for merging.

**Pull request merged**
