### PR TITLE
[#142] Update REST calls for 0.9.2

### PR DESCRIPTION
**Pull request by alanking**
- /zone_report endpoint is now /zonereport
- /zone_report POST method changed to GET
- /query POST method should be GET
- /query parameters changed in the following manner:
  - query_string -> query
  - query_limit -> limit
  - row_offset -> offset
  - query_type -> type

### CODE REVIEW

**Comment by alanking** [comment]
Ah, missed `case_sensitive` option in `/query`

**Comment by trel** [comment]
nice.   i will run/test and click around tonight/tomorrow.

since we don't have a proper testing framework for this GUI.

**Comment by alanking** [comment]
Turns out the underscores in our endpoint options were likely to accommodate the way Axios was being used in ZMT. Hyphens are not allowed when using the `params` interface for the `Axios` instance constructor because these are not allowed in Javascript identifiers (sorry if I'm using the wrong terms). So, I had to put it in the base URL, which felt wrong.

Didn't find anything online about this, so I'm not sure if it's supported or what can be done to get around it

**Comment by trel** [comment]
Hmm... that is very weird.   Okay, will require more investigation...

**Comment by korydraughn** [comment]
I was wondering about that change.

You can get around that by wrapping the property in single or double quotes. For example:
```js
params: {
    "case-sensitive": 0
}
```

**Comment by trel** [comment]
> You can get around that by wrapping the property in single or double quotes.

Oh?!  Yes, that seems good if true/available.

**Comment by alanking** [comment]
Totally works. Thanks @korydraughn !

**Comment by alanking** [comment]
Arguably, it would be better to be consistent about whether the params have quotations marks around them (none of the others do at this point in time) but I think this is okay for now? Willing to hit the rest as well if that seems worth doing

**Comment by trel** [comment]
i like consistency.   protect us from ourselves.

**Comment by alanking** [comment]
Backed out the quotation mark changes except where necessary. Also, squashed.

**Comment by trel** [comment]
Looks good to me - anything else concerning before # and merge?     Can always add another commit if we find something.

**Comment by trel** [comment]
oh, please rename src/data/checkfiles/default_checkfiles/rest-api-zone_report-endpoint.js to zonereport

**Comment by trel** [comment]
please # it when happy

**Comment by alanking** [comment]
\#'d

**Pull request merged**
