### PR TITLE
wip Zone Listview

### PR DESCRIPTION
**Pull request by connectbo**
alright, I made some progress on the zone listview. before I go too far away, feel free to take a look and suggest if any. 

Let's see... items on my to-do list
- pagination
- filter & sorting?
- input validation (name, connection) I did a little bit testing today and looks like rest cpp won't reject an empty name, host or comment... And it may interpret zone type 'remote' as a hostname if the name or host is empty.

### CODE REVIEW

**Comment by trel** [comment]
I removed the bad rows.   Yes, iRODS should behave better in light of bad data... but not today.

Please display the connection info as 'hostname' and 'port', two different columns.

Definitely need some 'empty string' prevention on the zonemae/hostname/port fields.
 - server should learn to prevent those as well

yes on sorting the columns

probably don't need filtering or pagination on the zones page for now.

maybe add the little color to the left edge, like on the /servers page... local zone gets the green and should always default to being listed first / top.

looking good.

**Comment by connectbo** [comment]
I added a couple of stuff here: sorting (local zone at the top by default), form validation (won't send request if zone name or hostname or port is empty), made a new column for port, and some green/grey color at the left edge. Did I miss anything here?

**Comment by trel** [comment]
looks good, sorts correctly, colors are nice.

consider a column that shows how many users are defined for each zone.  could be a background query to let them populate without holding up drawing the UI the first time(?).

also, need to think about whether we should allow deletion if the user count is greater than 0...   hmm.

should probably throw a warning/areyousure pop up on editing any of these rows... could be detrimental if there was an errant [enter] button hit...

**Comment by trel** [comment]
@alanking thoughts on deleting a remote zone if there are users defined in the catalog from that zone?   i guess that's equivalent to just renaming it out from under the users as well.   definitely needs some testing around that, and the fallout it might/would create.

**Comment by connectbo** [comment]
@trel I think it's ready for your review. Zone creation/deletion/modification should work as expected, confirmation popup and key event handlers are added and I polished the interface a little bit so zmt won't break when it comes to super long names.

**Comment by trel** [comment]
looking very good.

- port should be checked to be an integer greater than zero
- i see 7 users in local zone row, but there are 8 listed on the users page
- couldn't edit the zone name, save icon went grey, hmmm, alternates on which one i click...
- popup... let's not say 'warning'... how about 'Confirmation'... "Modifying zone thezonename..."

probably a separate issue/PR - but to the same issue...
 - the users page should now allow creating users in a remote zone (dropdown, local as default)
 - the users page should have a new column for zone (sortable)
 - editing a user should display the username at the top as user#zone

**Comment by trel** [comment]
easier to see the changes if you don't force push until we're done getting there :)

**Comment by connectbo** [comment]
yep sorry about that, I was trying to wrap up the /zones part and start to work on some related changes on the /users page, which I added to this pr as well. For this `editing a user should display the username at the top as user#zone`, I think we have something similar in the user management pr (not merged yet), I can change that to username#userzone if this is better. And probably that's it, let me know if I missed anything :)

**Comment by trel** [comment]
good
- icon greying out seems fixed
- confirmed user count is correct (8 vs 7, above)
- user zone column on users page

todo
- was still able to set a port to `23d` (not an integer)
- confirmation text still awkward - let's use "Modifying zone **thezonename**"
- the users page should now allow creating users in a remote zone (dropdown, local as default)
- editing a user should display the username at the top as `user#zone` (maybe happening in different PR)

**Comment by trel** [comment]
confirmed the remotezone addition now works (and port limitation, and confirmation text)

yes, let's fix the display in the other PR

please squash to 1-2 commits for 128, however it seems best.

**Comment by connectbo** [comment]
I think it's ready, should I add # ?

**Comment by trel** [comment]
ah, didn't see the new push.   yes, please # them both - thanks.

**Comment by connectbo** [comment]
yep added #

**Pull request merged**
