### PR TITLE
[72] sortable user column on group page

### PR DESCRIPTION
**Pull request by connectbo**
This pr should make the user column sortable on group page. 
- refactored the context provider to load user counts efficiently and decreased the number of api calls
- supported sorting by user counts

Let me know if anything comes to your mind. I will do more testing this afternoon, but feel free to take a look and break it :)

### CODE REVIEW

**Comment by connectbo** [comment]
ahh I see, when it's loading, only the loading indicator should be rendered. I will reproduce and fix it.

**Comment by connectbo** [comment]
Alright, I tried to reproduce the error and found that the previous rest api connection error was actually real, since there were a lot of concurrent requests, and rest api was telling us `connection is in use`. Refactored the order of api calls and it seems working as expected on my end. Please give it a try when you are free.

**Comment by trel** [comment]
yes, confirm I don't see that anymore - very nice.    please # it and we'll get it merged.

**Comment by connectbo** [comment]
yep, added

**Pull request merged**
