### PR TITLE
Created env variable for max number of servers displayed

### PR DESCRIPTION
**Pull request by ganning127**

### CODE REVIEW

**Comment by trel** [comment]
looks good.   please confirm this is behaving as expected by setting it to 1 in the settings and confirming only one is shown in the UI.      

oh, also, consider telling the user that the list is showing a max of X - so they know there may be more.   perhaps just 'above' the table listing.   alternative locations welcome.

**Comment by ganning127** [comment]
Ohhh okay, update. I made a mistake in what this variable means. The line `fullServersArray.slice(0, displayMaxNumberOfServers)` is actually setting how many servers are displayed on the initial render. Since on the table's page frontend, the default setting for "rows per page" is 10 (see below), we're doing `.slice(0, 10)` in the original code. 

Screenshot 2023-07-06 at 6 46 44 PM

It wouldn't really make sense to set this value to anything other than 10. Because even if we do (like in the screenshots below), if the user changes the "rows per page" setting to another value, the number of rows on that page will be at most the user set value out of the total. For example, if I had the env variable set to 1 at most, once the user uses the dropdown to select more rows per page, the other servers in the list will show.

**REACT_APP_DISPLAY_MAXIMUM_NUMBER_OF_SERVERS=10**
Screenshot 2023-07-06 at 6 17 25 PM

**REACT_APP_DISPLAY_MAXIMUM_NUMBER_OF_SERVERS=1**
Screenshot 2023-07-06 at 6 16 43 PM

Since the number of servers shown by default is 10, I'm thinking we should keep the max number of servers displayed at that value and not make it an env variable? We can maybe just add a comment explaining why its 10. Happy to do a live demo of this to make what I'm saying clearer.

**Comment by trel** [comment]
Oh, okay - so if there are 55 servers, there will be six pages (10 each) by default...

And we will always be able to see all the servers in the paged listing?   If we filter, does the filtering happen against all 55 or just the 10 that are currently displayed?

If all this makes sense and is good - I agree that we don't need a variable for this value.  A default of 10 seems fine.

Is that setting at the top 'sticky'?  If you pick a different number in the dropdown... does it get remembered on the next visit to this same page?  aka, is it stored in localStorage in the browser somehow?

**Comment by trel** [comment]
What do you think about remembering the number-to-show for each page type, independently?

If that seems like a good plan, let's close this PR, close https://github.com/irods/irods_client_zone_management_tool/issues/178, and make a new issue for remembering the settings.

**Comment by ganning127** [comment]
Yep, remembering the number to show for each page independently sounds like a better user experience. Will close this PR and make another issue!

**Comment by trel** [comment]
opened https://github.com/irods/irods_client_zone_management_tool/issues/181

**Pull request closed without merging**
