### PR TITLE
[68] support case-insensitive search

### PR DESCRIPTION
**Pull request by connectbo**
This pr is intended to allow case-insensitive search on `/user`, `/user/edit`, `/group`, `/group/edit`, `/resource` page. All search filters are capitalized and passed to rest API with the case-sensitive option set to 0.

### CODE REVIEW

**Comment by trel** [comment]
i see it working - when rebased on the other PR.    but i'm seeing '400 bad requests' in the console.

```
{"error_code":-10000,"error_message":"SYS_USER_NOT_ALLOWED_TO_CONN: connection already in use for token\n\n"}
```

**Comment by connectbo** [comment]
hmmm, I will see if I can reproduce this one.

**Comment by trel** [comment]
active/inactive is now merged, so rebase this ... and maybe it will appear for you.

**Comment by connectbo** [comment]
I didn't get '400 - connection in use error' on this one, can you try again and see if that error still occurs?

**Comment by connectbo** [comment]
That might relate to some changes in the previous pr. A new load of /home should load all your server data again which I see is 15 new requests on my end. Not sure why this happens, hmm maybe can we try logging out and have a fresh start?

**Comment by trel** [comment]
A clean reboot, logout/login, refresh of /home with dd18e6b

400-badrequests

**Comment by connectbo** [comment]
Yeah... we have the same setting, will investigate.

**Comment by trel** [comment]
i'm now seeing this without this code - it's happening on main.   So, I think this is probably ready to # and we can go ahead and merge it.   Something else is causing the 400s.

**Comment by trel** [comment]
yes, but we'll figure it out...

**Pull request merged**
