### PR TITLE
Refactored ZMT to communicate with HTTP API (main)

### PR DESCRIPTION
**Pull request by farbs03**

### CODE REVIEW

**Comment by farbs03** [comment]
Commits have been squashed

**Comment by korydraughn** [comment]
Good. Were you able to convert ALL functionality to use the HTTP API?

I believe there were a few operations that weren't supported by the HTTP API.

**Comment by farbs03** [comment]
I believe the only functionality that hasn't been implemented yet is for specific queries. I can work through that today and try to get another commit in for the pr.

**Comment by korydraughn** [comment]
Sounds good.

**Comment by farbs03** [comment]
All functionality should now be implemented.

**Comment by korydraughn** [comment]
Wonderful!

We'll leave this open so @trel has a chance to look over it.

**Comment by korydraughn** [comment]
Looks like we never covered modification of resources in this PR because the HTTP API didn't provide that at the time.

Support has been added to the HTTP API.

**Comment by trel** [comment]
I will try to build and run this today.

**Comment by trel** [comment]
I'm having trouble getting this to run - but I suspect (remote) docker networking is in my way.

I notice `REACT_APP_REST_API_URL` still in use, as well as `iRODS Client REST API` in the code.   Perhaps we can clean those up 'blindly' without me seeing it all run yet.

**Comment by trel** [comment]
pushed a few tweaks - looking real nice.

https://github.com/farbs03/irods_client_zone_management_tool/pull/1

**Comment by trel** [comment]
I think we're ready to discuss squashing down from 18 commits.   Open to ideas about the ideal number.   It could be 18.

**Comment by farbs03** [comment]
I already squashed mine down, so we could squash a few of yours. Maybe squash the 3 "rest to http" commits so we have 16 total?

**Comment by trel** [comment]
sure, please squash my 183s into one.

please keep the 185 separate.

**Comment by korydraughn** [comment]
Looks like the commits from @trel for 183 haven't been squashed. Please squash those two. There should be two commits from @trel once completed.

**Comment by farbs03** [comment]
Me and @trel ultimately decided to not squash all commits for 183, but some of them did get squashed. The current state of the commits is what we agreed on.

**Review by korydraughn — APPROVED** [review]
For commit 6771ef4974fb4955afeb45acc6f413195324dec3 ...
You can use /info to determine if the HTTP API is available. Open an issue for this.
The last bullet of that commit message talks about unixfilesystem and resc[6]. Open an issue for that so we don't forget to revisit that.

For commit 1020a6e08d6fbbcd3a7af3ad5252c3f01f00a7b3, open an issue for investigating the the SQL error.

Once the issues have been opened, pound it.

**Comment by farbs03** [comment]
The SQL error was resolved in a later commit, 2000ffa. Issues have been created for the other items mentioned.

**Comment by farbs03** [comment]
Commits have been pounded.

**Comment by korydraughn** [comment]
Excellent. Merging.

**Pull request merged**
