### PR TITLE
Health check Dashboard

### PR DESCRIPTION
**Pull request by connectbo**
Several changes have been made to the frontpage since the last demo:
- allow users to run single check / all checks by clicking the corresponding button
- by default, zmt will run all checks every five minutes or the context (zone, resc...) has changed
- each status will have its tag shown at the top, which also works as a filter

I do have a few tweaks (import & export, color palette..) left in my mind, but want to give you an overall feeling of how it works and looks. Feel free to run and I also captured some behaviors here. 

chrome-capture

### CODE REVIEW

**Comment by connectbo** [comment]
alright, I think it's ready for some click around. The 'Active' column are all checked for now (turn on or off checks), we will figure that out later. All health check components are modularized so it's very easy to export and import. I tried to make front-page dashboard looking, so we can add more metrics and functionality in the future.

**Comment by trel** [comment]
got it building again...

any idea why i'm seeing only two in the list, but the 'all' says there are 6 checks?

Screen Shot 2021-11-05 at 5 08 29 PM

also, i still see this not working... even though i see the 'fix' in the code...

- 'validate resource hostname' check should allow `EMPTY_RESC_HOST`

**Comment by connectbo** [comment]
hmm, I guess new check-file changes are not loaded. Can you try refreshing or logging out? So it will give you a fresh start.

**Comment by trel** [comment]
ah, a hard refresh / logout did it - i see six!  so yes, something about caching needs to be worked out.

**Comment by trel** [comment]
please add sorting to the status column, too.

i think i like 'error' rather than 'critical'.  and perhaps 'healthy' rather than 'ok'... can discuss.

**Comment by trel** [comment]
fresh build and reload, and seeing this now...

```
TypeError: Cannot read properties of undefined (reading 'length')
(anonymous function)
src/app/src/contexts/CheckContext.js:22
  19 | let context = { zoneContext, rescAll, restApiLocation, restApiTimeout }
  20 | 
  21 | useEffect(() => {
> 22 |     if (localStorage.getItem('zmt-token') && zoneContext.length !== 0 && checkResult.size === 0) {
  23 |         runAllCheck()
  24 |     }
  25 | }, [context])
```

**Comment by connectbo** [comment]
> fresh build and reload, and seeing this now...
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'length')
> (anonymous function)
> src/app/src/contexts/CheckContext.js:22
>   19 | let context = { zoneContext, rescAll, restApiLocation, restApiTimeout }
>   20 | 
>   21 | useEffect(() => {
> > 22 |     if (localStorage.getItem('zmt-token') && zoneContext.length !== 0 && checkResult.size === 0) {
>   23 |         runAllCheck()
>   24 |     }
>   25 | }, [context])
> ```
looked into this issue a little bit, seems like the preflight response doesn't include an `Access-Control-Allow-Origin` header, hence all Axios requests from localhost are blocked by cors.

**Comment by connectbo** [comment]
hmmm, are you pointing to the new vm or the old one?

**Comment by trel** [comment]
fixed the new vm, was an nginx config error on my part.

valid hostname check ... can it print out the 'invalid' hostname along with the violating resource name?

perhaps... 

`Failed: demoResc:unixfilesystem (bad_hostname), ufs2:unixfilesystem (localhost), pt2:passthru (example.org)`

bonus points if you can figure out how to hyperlink to the /resources page with it already filtered for that resource name.

**Comment by connectbo** [comment]
Definitely, let me play around with that idea.

**Comment by connectbo** [comment]
Alright, I think I've made some progress on the valid hostname check result printing - the format is updated and it will include a hyperlink (i.e. /resources?initialRescNameFilter=xxx). The resource list view will check if `initialRescNameFilter` arg is present, if yes then filter it; if not, load all resources. Feel free to click around and see if that works on your end.

**Comment by trel** [comment]
I like it.   Can we change the URL/parameter to read more simply `?filter=xxx`?

And then... as the person changes the filtering manually... the URL changes live, along with it?    Gives someone confidence they can copy/paste (or bookmark) that link and get back to it later.

**Comment by trel** [comment]
please rebase this against the chmod edit i merged, we've still got some delicate error cases to handle when configs are not perfect.  can be a separate PR.

**Comment by connectbo** [comment]
> I like it. Can we change the URL/parameter to read more simply `?filter=xxx`?
> 
> And then... as the person changes the filtering manually... the URL changes live, along with it? Gives someone confidence they can copy/paste (or bookmark) that link and get back to it later.

Poked around this a little bit, I love this idea. The param name is now changed to just filter, and I realize we should encode the filter value as well so URL would be valid (see resource `pt2?` ). Filter value changes should now be seen at the URL. Pulled in your chmod changes, please give it a try.

**Comment by trel** [comment]
works perfectly.    only bonus is if the filter is empty again, remove it from the URL completely.

i think with that change, you can squash the commits with issue numbers.    we'll # after confirmation.

**Comment by trel** [comment]
regarding your encoding thing (with a question mark...) we could also eventually just 'ignore' those characters... but encoding is easy enough for now.   thanks.

**Comment by trel** [comment]
In splitting the REST API endpoint checks... it no longer shows the configured endpoint URL itself.

Consider updating the endpoint checks to show...

`Description: Checks https://152.4.x.3:port/irods-rest/0.9.0/zone_report for non-5xx.`

**Comment by connectbo** [comment]
alright. ZMT will now remove the `filter` argument from the URL if it's empty, and each connection check will include the full endpoint URL. Please review and see if that's appropriate.

**Comment by trel** [comment]
all looks great.   please # these.

**Comment by connectbo** [comment]
added #

**Pull request merged**
