### PR TITLE
Bug/undefined input

### PR DESCRIPTION
**Pull request by connectbo**
Alright, this pr includes the fixes for several issues:
- [61] I remember we made those changes before but seems like we lost that part when making other changes. So I add them back. Sorry about that.
- [83] Set initial value (empty string '')  for each input value, so it won't be undefined.  
- [82] clicking the logout button will now wipe out the token stored in localstorage, and takes you back to the login page. So the logout view seems no longer needed and is removed. With that being said, I implemented that redirecting logic on unauthorized request for other pages as well, instead of rendering the logout view.

This pr also fixed a bug somehow related - When you change your url path to '/users/edit', where you will be after clicking 'EDIT' button on users page, there will be an error since we are not actually passing in the user data. The page will now takes you back to '/user' page. We previously rendered that '404 - page not found' view, but that seems incorrect and inefficient. Does that make sense?

That's a lot, feel free to play around and let me know your thoughts.

### CODE REVIEW

**Comment by trel** [comment]
so... empty string is not apparently quite right...    can we... *not* pass the hostname/vaultpath if they're empty?

This could also be a bug in the server (to see empty strings and consider them actually empty -> `EMPTY_RESC_HOST` and `EMPTY_RESC_PATH`)  @korydraughn ?

**Comment by trel** [comment]
something also weird going on with a colon (`:`) getting injected when the empty string is used on creation.

to reproduce, create a new passthru resource

**Comment by trel** [comment]
redirect logic seems good

**Comment by korydraughn** [comment]
> so... empty string is not apparently quite right... can we... _not_ pass the hostname/vaultpath if they're empty?
> 
> This could also be a bug in the server (to see empty strings and consider them actually empty -> `EMPTY_RESC_HOST` and `EMPTY_RESC_PATH`) @korydraughn ?

I'll investigate.

**Comment by connectbo** [comment]
alright, couple updates on this:
- ZMT will now check the hostname and vault path when creating new resource, 'Save' icon button will be disabled if hostname or vault path is empty. I also added a tooltip saying 'Hostname or Vault Path is not valid. Please check and try again' to better inform admin why they can't do that. (is the wording appropriate?) When both hostname and vault path fields are empty, it will be created and I do see EMPTY_RESC_HOST and EMPTY_RESC_PATH there. Nice!
- Key event are now supported when creating new resource/user/group. Clicking 'Add new resource' will take you out of editor mode if necessary, and vice versa, so there won't be any collision. 

Please review and let me know if that's a good approach.

**Comment by trel** [comment]
i'm seeing... the column sort doesn't work anymore on /resources?

**Comment by trel** [comment]
cannot seem to set either (or both) hostname and vault path to empty in the edit mode (not when creating a new resource).

**Comment by connectbo** [comment]
In editor mode, ZMT have to specify only one resource attribute (hostname or vault path or ...) that needs to change at one time, and send out api calls sequentially, which means modifying hostname and path will be two requests. ZMT does pass an empty string if you set either hostname or path to empty, but seems like rest api can't make that change and return a 400 error. 

I will look into the sorting issue..

**Comment by trel** [comment]
hmm, so the 'cannot set hostname or path to empty' could be a rest cpp bug...   or not...

```
$ iadmin modresc zzzz path ''
remote addresses: 172.31.2.221 ERROR: rcGeneralAdmin failed with error -816000 CAT_INVALID_ARGUMENT
```

so, maybe if you see an empty hostname or path, you can set it to `EMPTY_RESC_HOST` or `EMPTY_RESC_PATH`?   before sending to the API?   so nothing will ever have an empty string...

**Comment by trel** [comment]
seems to be working as expected now - very nice.

please squash / number as you like, and then we'll # em.

**Comment by connectbo** [comment]
Number added, will # if those looks good.

**Comment by connectbo** [comment]
Added, ready to merge.

**Pull request merged**
