### PR TITLE
[70] clickable column title

### PR DESCRIPTION
**Pull request by connectbo**
This pr
- made each table column title clickable and sortable
- mouse hover on each title will display its arrow

image

### CODE REVIEW

**Comment by trel** [comment]
looks good - works as expected.

please include numerical sort (not alpha) for the users column on the groups page.

and confirm it's numerical sort (not alpha) for resources column on servers page.

**Comment by connectbo** [comment]
ahh, sorting for users column, yeah we haven't supported that yet, as it is different from other columns we got from rest api. I can investigate and add this feature. 

Resource column on servers page is sorted numerically, confirmed.

**Comment by trel** [comment]
happy to get this merged and "make the groups->users column sortable" a new issue if you want.

**Comment by connectbo** [comment]
Sounds good, I will create a new issue. Adding # to this.

**Pull request merged**
