### PR TITLE
Add more error handling when rest api is down

### PR DESCRIPTION
**Pull request by connectbo**
This pr
- added loading indicator for each page(server/user/group/resource)
- catched rest api call error and added conditional rendering

image

### CODE REVIEW

**Comment by connectbo** [comment]
Please review and see if that makes sense. Also noted the /zone_report endpoint is down again(others are fine), is that a bug? I think it works well in the past.

**Comment by trel** [comment]
looks fine - way better than blowing up :)

something must be wrong on the REST API side - we'll see if there are any logs there.   I don't think there's anything that can be done on this end of that conversation.   @korydraughn i'll look for some logs on the REST side...

**Review by trel — APPROVED** [review]
add the # and we're good i think

**Comment by connectbo** [comment]
# added.

**Pull request merged**
