### PR TITLE
Feature/tree view

### PR DESCRIPTION
**Pull request by connectbo**
This pr 
- implemented draggable treeview under resource page. Supports drag and drop behavior to change the resource hierarchy.
- built tree and tree-item components. Each can be customized, nodes with too many child nodes can be folded.
- added staging for changes. Users can undo, redo or restore changes before submitting them.
- developed a popup to display each change details and its progress (awaiting, success or failed). Process will break if one move is failed.

Marked as draft for now, let me gather some feedback from our team member tomorrow :)

### CODE REVIEW

**Comment by trel** [comment]
looks pretty good.

please disallow dropping a node onto any of its own descendents (aka if `a-b-c`... `a` cannot be dropped on `b` or `c`)

**Comment by connectbo** [comment]
Thanks, I tweaked on this a little bit yesterday and came up with a solution. Will do some testing and let you know the progress.

**Comment by trel** [comment]
i like it - it correctly prevented me from dragging into any descendent or current parent.

1) dragging to current parent... maybe should just be ignored - it's not wrong, it's just a 'no-op'?

2) please consider switching the 'YES' and 'NO' buttons on the modal confirmation window.    Can you move 'NO' to the left side, to get it a little farther away from 'YES'?

3) the tiny 'x' in a square in front of each leaf resource... makes it seem like something is 'wrong'... can you try to use the same '-' icon as the others, just grayed out, like the 'x'?

Screen Shot 2021-07-07 at 11 36 21 AM

**Comment by connectbo** [comment]
I think you are right. Yeah, it's just no operation instead an invalid move. I will refine these!

**Comment by trel** [comment]
very nice.    i like the new hover information as well, feels clean.

1) please get that NO button away from the YES button a bit more :)    can you put it on the left side?

3) please change the dialog question from
"Are you sure to make the following changes?"
to
"Are these changes correct?"

**Comment by trel** [comment]
looks good.     anything else before we get ready to merge this?

**Comment by trel** [comment]
if not, please squash down to a single commit and point at [36]

**Comment by connectbo** [comment]
Oh, I left a question for you in Slack :) Can put it here as well, do we want extra space between each resource?

**Comment by trel** [comment]
please update the commit description to be additional info, or just remove it all.   don't want all those extra lines from the intermediate commits.

**Comment by connectbo** [comment]
oops.. Forgot about that, making changes now.

**Comment by connectbo** [comment]
I added a short description to this commit. Let me know if that works :)

**Comment by trel** [comment]
yes, add a line of whitespace before the description, and then you can # it too.

**Pull request merged**
