### PR TITLE
add 404 page and cleanup the router

### PR DESCRIPTION
**Pull request by connectbo**
This pr
- add a new responsive 404 error page if the pathname is not matched
- refactor the import/export logic so the router looks cleaner

While I am starting to prioritize those items I listed, I think zmt should have this error page. One question I have is - shall I create a new issue for this? Then our epic checklist can be a list of issues. Is that a good approach?

Screenshot for the 404 page: Clicking on 'homepage' will take you back to '/' basepath, and depending on you have logged in or not, router will take you to homepage(dashboard) or login page.
image

### CODE REVIEW

**Comment by trel** [comment]
yes, to the general sentiment.         page should probably say something about '404'.

and then the logo is a link back to '/'?

design something cool :)

**Comment by trel** [comment]
getting there.

Let's...
- add a line of whitespace before 'ERROR 404'
- remove the last line, linking to homepage.
- make the text read 'The requested URL was not found on this server:'
- then the next line is just '/nasdf' (since it could be relatively long...)

**Comment by connectbo** [comment]
yeah I agree, having pathname on a new line is better. I made some adjustments there:

image

Does that look cool?

**Comment by trel** [comment]
yep looks good - let's merge it.

**Comment by connectbo** [comment]
cool, I got # added, ready for merging.

**Pull request merged**
