### PR TITLE
Stopped servers page from crashing when clicking on `Details` (main)

### PR DESCRIPTION
**Pull request by ganning127**
Shows up fine now:

Screenshot 2023-07-03 at 6 03 08 PM

also changed the active tab coloring to be more clear that you can click on different tabs:

Screenshot 2023-07-03 at 6 09 26 PM

### CODE REVIEW

**Comment by trel** [comment]
oh, i see - we were keying off a file that no longer exists with the move to v4/4.3.1...

so this is not happening when pointing to a 4.3.0 and prior server?

**Comment by ganning127** [comment]
I haven't tried prior to 4.3.0 yet, but irods_demo is running 4.3.0 and the page crash when clicking "details" still happens.

**Comment by trel** [comment]
Got it - yes.   4.2.x would work fine - before this file was absorbed into the main server_config in 4.3.0.

**Comment by ganning127** [comment]
Just tested this code with the new ZMT handling for 4.3.1. This bug fix will work for both 4.3.1 (new zonereport format) and before.

**Comment by trel** [comment]
please squash to one and reconfirm all is good.   we can get this merged soon too.

**Comment by ganning127** [comment]
can confirm that this works for both the 4.3.0 and 4.3.1 zonereports.

**Comment by trel** [comment]
nice.   please tweak commit message to say 'why', and not just 'what'.

perhaps... "fix crash by ..."

**Comment by ganning127** [comment]
changed commit message!

**Comment by trel** [comment]
lovely, please #.

**Comment by ganning127** [comment]
added #

**Pull request merged**
