### PR TITLE
Bug/fix user counts

### PR DESCRIPTION
**Pull request by connectbo**
This pr refactor the way we load user counts, and will always pull down the latest user counts of a group. Can be merged after the other two. Marked as WIP for now.

### CODE REVIEW

**Comment by trel** [comment]
i think this can be rebased and perhaps squashed...

**Comment by connectbo** [comment]
rebased this one. should I # ?

**Comment by trel** [comment]
double commit message.   get it to one line, and yes.

**Comment by connectbo** [comment]
ahh right, thanks for catching that! I cleaned up and added #.

**Pull request merged**
